/// Flutter icons Restaurante
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Restaurante
///      fonts:
///       - asset: fonts/Restaurante.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class Restaurante {
  Restaurante._();

  static const _kFontFam = 'Restaurante';
  static const String? _kFontPkg = null;

  static const IconData credit_card = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ticket_alt = IconData(
    0xf3ff,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData money_bill_wave = IconData(
    0xf53a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
